<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admin-PC" name="com.zoopla.qa.TestCases.SalesPageTest" tests="4" failures="1" timestamp="18 Aug 2019 15:31:28 GMT" time="75.532" errors="0">
  <testcase name="verityZooplaLogo" time="18.522" classname="com.zoopla.qa.TestCases.SalesPageTest"/>
  <testcase name="verifySalesPageTitle" time="18.510" classname="com.zoopla.qa.TestCases.SalesPageTest">
    <failure type="java.lang.AssertionError" message="expected [Property for Sale in London - Buy Properties in London - Zoopla11] but found [Property for Sale in London - Buy Properties in London - Zoopla]">
      <![CDATA[java.lang.AssertionError: expected [Property for Sale in London - Buy Properties in London - Zoopla11] but found [Property for Sale in London - Buy Properties in London - Zoopla]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.zoopla.qa.TestCases.SalesPageTest.verifySalesPageTitle(SalesPageTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- verifySalesPageTitle -->
  <testcase name="printListValues" time="16.080" classname="com.zoopla.qa.TestCases.SalesPageTest"/>
  <testcase name="clickOnPositionValue" time="22.420" classname="com.zoopla.qa.TestCases.SalesPageTest"/>
</testsuite> <!-- com.zoopla.qa.TestCases.SalesPageTest -->
